### ISSUE TITLE
DynamoDB

### ISSUE THREAD

**Issue by oliverbhull** [alexa-samples/skill-sample-nodejs-adventure-game#2]
Changes made by the user don't log in DynamoDB.
The Lambda trigger appears to be working fine but no records are being processed by the Dynamo Table.

**Comment by rjamison** [comment]
Could you check the logs for your Lambda function to see if there are any errors?  

One possibility is that the AWS Role you setup for the function doesn't have access to create the table in DynamoDB, in which case you should see an AWS error message in your logs.

Another is that a DynamoDB table name isn't defined, in which case you should see an error message like:

`ERROR: Dynamo DB table name was not provided`

**Comment by rjamison** [comment]
@oliverbhull are you still having the issue?  Happy to help if you can provide more detail.

**Comment by AWzone** [comment]
I'm having the same issue, with this error in the CloudWatch log:
{
    "message": "One or more parameter values were invalid: Missing the key userid in the item",
    "code": "ValidationException",
    "time": "2016-08-27T17:11:15.198Z",
    "requestId": "4D9QR2LA8R55QH70H5IE1QQUE7VV4KQNSO5AEMVJF66Q9ASUAAJG",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 0
}

**Comment by rjamison** [comment]
@AWzone looks like you have the wrong case in the key for your DynamoDB table.  "userid" should be "userId".

**Comment by AWzone** [comment]
Of course! Thanks for spotting that. I checked it against the screenshot and didn't see the error. 😂
